---

- name: Ensure k3s_build_cluster is false if running against a single node.
  ansible.builtin.set_fact:
    k3s_build_cluster: false
  when:
    - ansible_play_hosts | length < 2
    - k3s_registration_address is not defined

- name: Ensure k3s control node fact is set
  ansible.builtin.set_fact:
    k3s_control_node: "{{ not k3s_build_cluster }}"
  when: k3s_control_node is not defined

- name: Ensure k3s primary control node fact is set
  ansible.builtin.set_fact:
    k3s_primary_control_node: "{{ not k3s_build_cluster }}"
  when: k3s_primary_control_node is not defined

- name: Ensure k3s control plane port is captured
  ansible.builtin.set_fact:
    k3s_control_plane_port: "{{ k3s_runtime_config['https-listen-port'] | default(6443) }}"
  delegate_to: k3s_primary_control_node

- name: Ensure k3s node IP is configured when node-ip is defined
  ansible.builtin.set_fact:
    k3s_node_ip: "{{ k3s_runtime_config['node-ip'] }}"
  when:
    - k3s_runtime_config['node-ip'] is defined

- name: Ensure a count of control nodes is generated from ansible_play_hosts
  ansible.builtin.set_fact:
    k3s_controller_list: "{{ k3s_controller_list + [ item ] }}"
  when:
    - hostvars[item].k3s_control_node is defined
    - hostvars[item].k3s_control_node
  loop: "{{ ansible_play_hosts }}"

- name: Ensure a k3s control node is defined if none are found in ansible_play_hosts
  block:

    - name: Set the control host
      ansible.builtin.set_fact:
        k3s_control_node: true
      when: inventory_hostname == ansible_play_hosts[0]

    - name: Ensure a count of control nodes is generated
      ansible.builtin.set_fact:
        k3s_controller_list: "{{ k3s_controller_list + [ item ] }}"
      when:
        - hostvars[item].k3s_control_node is defined
        - hostvars[item].k3s_control_node
      loop: "{{ ansible_play_hosts }}"

  when:
    - k3s_controller_list | length < 1
    - k3s_build_cluster is defined
    - k3s_build_cluster

- name: Ensure a primary k3s control node is defined if multiple are found in ansible_play_hosts
  ansible.builtin.set_fact:
    k3s_primary_control_node: true
  when:
    - k3s_controller_list is defined
    - inventory_hostname == k3s_controller_list[0]
    - k3s_build_cluster is defined
    - k3s_build_cluster

- name: Ensure ansible_host is mapped to inventory_hostname
  ansible.builtin.blockinfile:
    path: /tmp/inventory.txt
    block: |
      {% for host in ansible_play_hosts %}
      {% filter replace('\n', ' ') %}
      {{ host }}
      @@@
      {{ hostvars[host].ansible_host | default(hostvars[host].ansible_fqdn) | string }}
      @@@
      C_{{ hostvars[host].k3s_control_node | string }}
      @@@
      P_{{ hostvars[host].k3s_primary_control_node | default(False) | string }}
      {% endfilter %}
      @@@ END:{{ host }}
      {% endfor %}
    create: true
    mode: 0600
  check_mode: false
  when: k3s_control_node is defined

- name: Delegate an initializing control plane node
  block:
    - name: Lookup control node from file
      ansible.builtin.command:
        cmd: "grep -i '{{ 'P_True' if (k3s_controller_list | length > 1) else 'C_True' }}' /tmp/inventory.txt"
      changed_when: false
      check_mode: false
      register: k3s_control_delegate_raw

    - name: Ensure control node is delegated for obtaining a cluster token
      ansible.builtin.set_fact:
        k3s_control_delegate: "{{ k3s_control_delegate_raw.stdout.split(' @@@ ')[0] }}"
      check_mode: false
      when: k3s_control_delegate is not defined

    - name: Ensure the node registration address is defined from k3s_control_node_address
      ansible.builtin.set_fact:
        k3s_registration_address: "{{ k3s_control_node_address }}"
      check_mode: false
      when: k3s_control_node_address is defined

    - name: Ensure the node registration address is defined from node-ip
      ansible.builtin.set_fact:
        k3s_registration_address: "{{ hostvars[k3s_control_delegate].k3s_node_ip }}"
      check_mode: false
      when:
        - k3s_registration_address is not defined
        - k3s_control_node_address is not defined
        - hostvars[k3s_control_delegate].k3s_node_ip is defined

    - name: Ensure the node registration address is defined
      ansible.builtin.set_fact:
        k3s_registration_address: "{{ hostvars[k3s_control_delegate].ansible_host | default(hostvars[k3s_control_delegate].ansible_fqdn) }}"
      check_mode: false
      when:
        - k3s_registration_address is not defined
        - k3s_control_node_address is not defined

  when: k3s_registration_address is not defined
        or k3s_control_delegate is not defined
