---

- name: Ensure k3s service is started
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: "{{ k3s_start_on_boot }}"
  when: k3s_non_root is not defined or not k3s_non_root
  become: "{{ k3s_become }}"

- name: Ensure k3s service is started
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: "{{ k3s_start_on_boot }}"
    scope: user
  when:
    - k3s_non_root is defined
    - k3s_non_root
  become: "{{ k3s_become }}"
