---

- name: Check that the control plane is available to accept connections
  ansible.builtin.wait_for:
    port: "{{ k3s_runtime_config['https-listen-port'] | default('6443') }}"
    host: "{{ k3s_runtime_config['bind-address'] | default('127.0.0.1') }}"
    delay: 5
    sleep: 5
    timeout: 300
  when: k3s_control_node
