---

- name: Check if any experimental variables are configure and if they are enabled with k3s_use_experimental
  assert:
    that:
      - k3s_use_experimental is defined and k3s_use_experimental
    success_msg: "Experimental variables are defined and enabled."
    fail_msg: "Experimental variables have been configured. If you want to use them ensure you set k3s_use_experimental"
  when: (k3s_non_root is defined and k3s_non_root)
        or (k3s_dqlite_datastore is defined and k3s_dqlite_datastore)
        or (k3s_etcd_datastore is defined and k3s_etcd_datastore and (k3s_release_version | replace('v', '')) is version('1.19.5', '<'))
        or (k3s_secrets_encryption is defined and k3s_secrets_encryption)
        or (k3s_enable_selinux is defined and k3s_enable_selinux and (k3s_release_version | replace('v', '')) is version('1.19.4', '<'))

- name: Check if experimental dqlite is being used and k3s_use_unsupported_config is configured
  assert:
    that:
      - k3s_use_unsupported_config is defined and k3s_use_unsupported_config
    success_msg: "Unsupported use of dqlite backend is enabled."
    fail_msg: |
      Embedded DQLite is no longer supported and there is no upgrade path to use Etcd!
      If you're sure you want to use it set k3s_use_unsupported_config. This will break in v1.19!
  when: k3s_use_experimental
    and (k3s_dqlite_datastore is defined and k3s_dqlite_datastore)
