---

- name: Check that k3s_state is a supported value
  ansible.builtin.assert:
    that:
      - k3s_state in k3s_valid_states
    fail_msg: "k3s_state not valid. Check README.md for details."
    success_msg: "k3s_state is valid."
  when: k3s_state is defined

- import_tasks: environment/local/packages.yml
  when:
    - not k3s_skip_validation
    - not k3s_skip_env_checks

- include_tasks: environment/remote/cgroups.yml
  loop: "{{ k3s_cgroup_subsys }}"
  loop_control:
    loop_var: cgroup
  when:
    - not k3s_skip_validation
    - not k3s_skip_env_checks

- include_tasks: environment/remote/packages.yml
  loop: "{{ k3s_check_packages }}"
  loop_control:
    loop_var: package
  when:
    - not k3s_skip_validation
    - not k3s_skip_env_checks

- include_tasks: environment/local/issue-data.yml
  when:
    - pyratlabs_issue_controller_dump is defined
    - pyratlabs_issue_controller_dump
