---

- name: Check to see if k3s_state is a supported value
  assert:
    that:
      - k3s_state in k3s_valid_states
    fail_msg: "k3s_state not valid. Check README.md for details."
    success_msg: "k3s_state is valid."
  when: k3s_state is defined

- import_tasks: generate-check-config.yml

- import_tasks: check-environment.yml
  when: not k3s_skip_validation
