---

- name: Check that {{ package.name }} is installed
  ansible.builtin.command:
    cmd: "which {{ package.name }}"
  changed_when: false
  failed_when: false
  register: check_k3s_required_package

- name: Test that checks for {{ package.name }} passed
  ansible.builtin.assert:
    that:
      - check_k3s_required_package.rc == 0
    success_msg: "Found required package: {{ package.name }}."
    fail_msg: >-
      Could not find package: {{ package.name }}.
      {% if package.documentation is defined %}
      Documentation: {{ package.documentation }}
      {% endif %}
  when:
    - (package.until is not defined
       or k3s_release_version is version_compare(package.until, '>='))
    - (package.from is not defined
       or k3s_release_version is version_compare(package.from, '>='))
